platform :ios, '10.0'
inhibit_all_warnings!
use_frameworks!
install! 'cocoapods'

targets = ['Demo', 'Demo2']

targets.each do |t|
  target t do
    pod 'SwiftLint'
    pod 'AlamofireImage'
    
    pod 'InputBarAccessoryView'    
  end
end

# fix warning
post_install do |installer|
  installer.pods_project.build_configurations.each do |config|
    config.build_settings['CLANG_ANALYZER_LOCALIZABILITY_NONLOCALIZED'] = 'YES'
  end
end
